server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/online-course-authuser
    username: postgres
    password: pass123
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgresSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true